name: "Setup a Specific Dart SDK Version"
description: "Setup the Dart SDK, and add it to the PATH"
inputs:
  channel:
    description: "The release channel to install from ('stable', 'stable@version', 'beta', or 'dev')"
    required: false
    default: "stable"
runs:
  using: "composite"
  steps:
    - run: $GITHUB_ACTION_PATH/setup.sh ${{ inputs.channel }} ${{ runner.os }}
      shell: bash
