name: over_react
version: 4.1.0
description: A library for building statically-typed React UI components using Dart.
homepage: https://github.com/Workiva/over_react/
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  collection: ^1.14.11
  analyzer: ^1.7.0
  build: ^1.0.0
  dart_style: ^1.2.5
  js: ^0.6.1+1
  logging: ">=0.11.3+2 <1.0.0"
  memoize: ^2.0.0
  meta: ^1.1.6
  path: ^1.5.1
  react: ^6.0.0
  redux: ">=3.0.0 <5.0.0"
  source_span: ^1.4.1
  transformer_utils: ^0.2.6
  w_common: ^1.13.0
  w_flux: ^2.10.4
  platform_detect: ^1.3.4
  quiver: ">=0.25.0 <3.0.0"
  redux_dev_tools: ">=0.4.0 <0.6.0"

dev_dependencies:
  build_resolvers: ^1.0.5
  build_runner: ^1.7.1
  build_test: any
  build_web_compilers: ^2.5.1
  dart2_constant: ^1.0.0
#  dart_dev: ^3.6.4
  glob: ^2.0.0
  io: ^0.3.2+1
  mockito: ^4.1.1
  over_react_test: ^2.10.2
  pedantic: ^1.8.0
  test: ^1.9.1
  yaml: ^3.0.0

dependency_overrides:
  # Needed because of transformer_utils
  analyzer: ^1.7.0
  # Needed because of platform_detect
  pub_semver: ^1.0.0
  react:
    git:
      url: https://github.com/Workiva/react-dart.git
      ref: null-safety-manual


workiva:
  core_checks:
    version: 1
    react_boilerplate: disabled
