name: over_react_plugin_loader_local
version: 0.0.0
description: This pubspec determines the version of the analyzer plugin to load. It needs to be in `tools/analyzer_plugin`
environment:
  sdk: '>=1.24.0-dev.1.0'
dependencies:
  over_react_analyzer_plugin:
    # This has to be absolute since this pubspec.yaml gets copied to a temp folder and then resolved
    # Update to your local checkout
    path: /Users/greglittlefield/workspaces/over_react_analyzer_plugin/over_react_analyzer_plugin
