name: todo_client
version: 1.0.0

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  color: any
  over_react: ^3.1.5
  redux: ^3.0.0
  redux_dev_tools: 0.4.0
  uuid: ^1.0.3

dev_dependencies:
  w_common: ^1.20.0
  over_react_test: ^2.0.0
  build_runner: ^1.7.1
  build_web_compilers: ^2.5.1
  json_serializable: ^2.0.0
  pedantic: ^1.8.0
