name: plugin_playground
version: 0.0.0
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  over_react: ^3.5.3
dev_dependencies:
  build_runner: ^1.0.0
  build_web_compilers: ^2.0.0
  workiva_analysis_options: ^1.1.0

dependency_overrides:
  react:
    git:
      url: https://github.com/cleandart/react-dart.git
      ref: 6.0.0-wip
  # Pull in the local copy of over_react so it pulls in the local copy of the plugin  over_react:
    git:
      url: https://github.com/Workiva/over_react.git
      ref: release_over_react_4.0.0

