name: over_react_analyzer_plugin
version: 0.1.0
description: Dart analyzer plugin for OverReact
homepage: https://github.com/greglittlefield-wf/git_playground/tree/over_react_analyzer_plugin/master
authors:
  - Greg Littlefield <greg.littlefield@workiva.com>
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  analyzer: '^0.39.10'
  analyzer_plugin: '^0.2.4'
  dart_dev: ^3.0.0
  # Upon release, this should be pinned to the over_react version from ../../pubspec.yaml
  # so that it always resolves to the same version of over_react that the user has pulled in,
  # and thus has the same boilerplate parsing code that's running in the builder.
  over_react: 3.5.3
  meta: ^1.1.6
  path: ^1.5.1
dev_dependencies:
  workiva_analysis_options: ^1.1.0

# For development, point to the local copy of over_react.
#
# This should be removed before publishing
dependency_overrides:
  over_react:
    path: ../..
