name: over_react_plugin_loader_path
version: 0.0.0
description: A loader for a local version of the plugin located at a specific path.
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  over_react_analyzer_plugin:
    # This has to be absolute since this pubspec.yaml gets copied to a temp folder and then resolved
    # Update to your local checkout
    path: /Users/greglittlefield/workspaces/over_react_analyzer_plugin/over_react_analyzer_plugin
