name: over_react_analyzer_plugin
version: 0.1.0
description: Dart analyzer plugin for OverReact
homepage: https://github.com/greglittlefield-wf/git_playground/tree/over_react_analyzer_plugin/master
authors:
  - Greg Littlefield <greg.littlefield@workiva.com>
environment:
  sdk: '>=2.6.0 <=3.0.0'
dependencies:
  analyzer: '>=0.38.0 <0.40.0'
  analyzer_plugin: '^0.2.1'
  dart_dev: ^2.0.0
  meta: ^1.1.6
  path: ^1.5.1
dev_dependencies:
  pedantic: ^1.5.0
