name: over_react_analyzer_plugin
version: 0.1.0
description: Dart analyzer plugin for OverReact
homepage: https://github.com/greglittlefield-wf/git_playground/tree/over_react_analyzer_plugin/master
authors:
  - Greg Littlefield <greg.littlefield@workiva.com>
environment:
  sdk: '>=2.1.0 <=3.0.0'
dependencies:
  analyzer: '>=0.33.3 <0.36.0'
  analyzer_plugin: '>=0.0.1-alpha.5 <0.0.1-alpha.8'
  meta: ^1.1.6
  path: ^1.5.1
dev_dependencies:
  pedantic: ^1.5.0
